### ISSUE TITLE
T:System.String in "Strings" and "Tuples" articles

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharpdocs#102] opened 2016-05-26 07:40 UTC
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/strings-%5bfsharp%5d

![image](https://cloud.githubusercontent.com/assets/873919/15567314/4a373966-232e-11e6-9f5d-a90e04b15bc6.png)

also at the bottom

![image](https://cloud.githubusercontent.com/assets/873919/15567334/6be4be30-232e-11e6-948a-d4d364419d17.png)

and in Tuples article https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/tuples-[fsharp]

![image](https://cloud.githubusercontent.com/assets/873919/15567489/53a72a8c-232f-11e6-9b09-84b293014ec9.png)

**Comment by ReedCopsey** [comment] 2016-05-26 14:47
This is a duplicate of #61. I'll get it eventually with those cleanups.

**Comment by dend** [comment] 2016-05-30 00:58
Fixed in #128

**Closed by dend** 2016-05-30 00:58 UTC
Labels: bug
