### ISSUE TITLE
Authoritative formatting guidelines/example

### ISSUE THREAD

**Issue by Vandroiy** [Microsoft/visualfsharpdocs#123] opened 2016-05-27 23:04 UTC
I have no idea how to format files correctly. There are just too many inconsistencies and broken pieces to infer how it's supposed to look. I think guidelines or correctly formatted examples would help.

For example: What heading levels are used for what content? How are exceptions documented? How is code or output indented? Are return values really supposed to be written in bold, without caption, right after the last parameter? How should parameters be formatted? Should examples really be preceded by a boilerplate sentence instead of an "Example" heading? How much can/should the initial description text for a function entail, where should a longer explanation go? There's excessive use of bold text in place of headings, should we be doing that?

I simply copied styles from random files for my first PRs, but I see now that this might just be adding to the chaos.

**Comment by ReedCopsey** [comment] 2016-05-27 23:10
This was self-assigned by @dend in #57 - This is effectively a duplicate of that issue.

**Comment by Vandroiy** [comment] 2016-05-27 23:23
@ReedCopsey Argh, how did I miss that? Sorry, I should get enough sleep before posting. I better call if quits for now before I flood the place.

**Comment by dend** [comment] 2016-05-29 16:04
@Vandroiy thanks for bringing this up to our attention! As @ReedCopsey already mentioned, I am working on it. I started some parts of that in the [Wiki](https://github.com/Microsoft/visualfsharpdocs/wiki/Authoring-documentation). Check out the sidebar for details, more to come.

**Closed by dend** 2016-05-29 16:04 UTC
